# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DxtwjwGDMrxaJNyVxjsT_NpqkB86YCv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

file_path = list(uploaded.keys())[0]

train = pd.read_excel(file_path, sheet_name="Training_Data")
test = pd.read_excel(file_path, sheet_name="Test_Data")

print("Training data:", train.shape)
print("Test data:", test.shape)

train.head()

train.tail()

train.sample(10)

print("TRAINING DATA INFO")
print("-" * 50)
train.info()

print("\n" + "=" * 50)

print("TEST DATA INFO")
print("-" * 50)
test.info()

print("MISSING VALUES IN TRAINING DATA")
print(train.isnull().sum())

print("\nMISSING VALUES IN TEST DATA")
print(test.isnull().sum())

missing_train = pd.DataFrame({
    "Missing_Count": train.isnull().sum(),
    "Missing_Percentage": (train.isnull().sum() / len(train)) * 100
})

missing_train = missing_train[missing_train["Missing_Count"] > 0]

print("Missing values in training data:")
display(missing_train.sort_values("Missing_Percentage", ascending=False))

print("Exact duplicate rows in training data:", train.duplicated().sum())
print("Exact duplicate rows in test data:", test.duplicated().sum())

print(train.columns.tolist())

train_features = train.drop(columns=["Test_ID"])
test_features = test.drop(columns=["Test_ID"])

print("Duplicate measurement records in training data:",
      train_features.duplicated().sum())

print("Duplicate measurement records in test data:",
      test_features.duplicated().sum())

train.describe()

test.describe()

train["Validity_Label"].value_counts()

sns.countplot(data=train, x="Validity_Label")
plt.title("Valid vs Invalid Records")
plt.show()

numeric_columns = [
    "Applied_Voltage_kV",
    "Load_Current_A",
    "Ambient_Temperature_C",
    "Test_Duration_min",
    "Sensor_S1",
    "Sensor_S2",
    "Sensor_S3",
    "Sensor_S4",
    "Reference_Parameter"
]
train[numeric_columns].describe().T
for column in numeric_columns:
    plt.figure(figsize=(7, 4))
    sns.histplot(data=train, x=column, kde=True)
    plt.title(f"Distribution of {column}")
    plt.show()

for column in numeric_columns:
    plt.figure(figsize=(7, 3))
    sns.boxplot(x=train[column])
    plt.title(f"Boxplot of {column}")
    plt.show()

correlation = train[numeric_columns].corr()

correlation["Reference_Parameter"].sort_values(ascending=False)

plt.figure(figsize=(12, 8))

corr = train[numeric_columns].corr()

sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(7, 5))

sns.scatterplot(
    data=train,
    x="Load_Current_A",
    y="Reference_Parameter",
    hue="Validity_Label"
)

plt.title("Load Current vs Reference Parameter")
plt.show()

sensor_columns = [
    "Sensor_S1",
    "Sensor_S2",
    "Sensor_S3",
    "Sensor_S4"
]

for sensor in sensor_columns:

    plt.figure(figsize=(7, 5))

    sns.scatterplot(
        data=train,
        x=sensor,
        y="Reference_Parameter",
        hue="Validity_Label"
    )

    plt.title(f"{sensor} vs Reference Parameter")
    plt.show()

train.groupby("Validity_Label")[numeric_columns].mean()
train.groupby("Validity_Label")[numeric_columns].median()

for column in numeric_columns:

    plt.figure(figsize=(7, 4))

    sns.boxplot(
        data=train,
        x="Validity_Label",
        y=column
    )

    plt.title(f"{column}: Valid vs Invalid")
    plt.show()

train["S1_S2_diff"] = train["Sensor_S1"] - train["Sensor_S2"]
train["S1_S3_diff"] = train["Sensor_S1"] - train["Sensor_S3"]
train["S2_S3_diff"] = train["Sensor_S2"] - train["Sensor_S3"]

train.groupby("Validity_Label")[
    ["S1_S2_diff", "S1_S3_diff", "S2_S3_diff"]
].mean()

sns.boxplot(
    data=train,
    x="Validity_Label",
    y="S1_S2_diff"
)

plt.show()

print(train["Validity_Label"].value_counts())
print(train["Validity_Label"].value_counts(normalize=True) * 100)

plt.figure(figsize=(6,4))

sns.countplot(data=train, x="Validity_Label")

plt.title("Valid vs Invalid Records")
plt.xlabel("Validity Label")
plt.ylabel("Number of Records")

plt.show()

#feature distribution
train[numeric_columns].hist(
    figsize=(16, 12),
    bins=30
)

plt.tight_layout()
plt.show()

train[numeric_columns].describe().T

correlation = train[numeric_columns].corr()
correlation["Reference_Parameter"].sort_values(ascending=False)

train.groupby("Validity_Label")[numeric_columns].mean().T

# Check missing values by Validity Label

missing_by_label = train.groupby("Validity_Label")[
    ["Sensor_S1", "Sensor_S2", "Sensor_S3", "Sensor_S4"]
].apply(lambda x: x.isna().sum())

print(missing_by_label)

# Percentage of missing values within each validity class

for label in train["Validity_Label"].unique():
    subset = train[train["Validity_Label"] == label]

    print("\n", label)
    print(subset[
        ["Sensor_S1", "Sensor_S2", "Sensor_S3", "Sensor_S4"]
    ].isna().sum())

#check outliner
plt.figure(figsize=(15, 8))
train[numeric_columns].boxplot()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#compare valid vs invalid
comparison = train.groupby("Validity_Label")[numeric_columns].mean().T

print(comparison)

# Check sensor behavior
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

sensors = ["Sensor_S1", "Sensor_S2", "Sensor_S3", "Sensor_S4"]

for ax, sensor in zip(axes.flatten(), sensors):
    for label in ["Valid", "Invalid"]:
        subset = train[train["Validity_Label"] == label]
        ax.scatter(
            subset[sensor],
            subset["Reference_Parameter"],
            label=label,
            alpha=0.5
        )

    ax.set_xlabel(sensor)
    ax.set_ylabel("Reference Parameter")
    ax.legend()

plt.tight_layout()
plt.show()

# check training vs test data
feature_columns = [
    "Applied_Voltage_kV",
    "Load_Current_A",
    "Ambient_Temperature_C",
    "Test_Duration_min",
    "Sensor_S1",
    "Sensor_S2",
    "Sensor_S3",
    "Sensor_S4"
]

print("TRAINING DATA")
print(train[feature_columns].describe().T)

print("\nTEST DATA")
print(test[feature_columns].describe().T)

feature_columns = [
    "Applied_Voltage_kV",
    "Load_Current_A",
    "Ambient_Temperature_C",
    "Test_Duration_min",
    "Sensor_S1",
    "Sensor_S2",
    "Sensor_S3",
    "Sensor_S4"
]

train[feature_columns] = train[feature_columns].apply(
    pd.to_numeric, errors="coerce"
)

test[feature_columns] = test[feature_columns].apply(
    pd.to_numeric, errors="coerce"
)

for col in feature_columns:
    median_value = train[col].median()

    train[col] = train[col].fillna(median_value)
    test[col] = test[col].fillna(median_value)

print("Training duplicates:", train.duplicated().sum())
print("Test duplicates:", test.duplicated().sum())

# ============================================================
# PREPROCESSING - STEP 1
# Create a separate copy of the original training data
# ============================================================

cleaned_train = train.copy()

print("Original training shape:", train.shape)
print("Working preprocessing shape:", cleaned_train.shape)

# ==========================================
# STEP 2 - Reload ORIGINAL training data
# ==========================================

train_raw = pd.read_excel(
    file_path,
    sheet_name="Training_Data"
)

# Make a fresh working copy
cleaned_train = train_raw.copy()

sensor_columns = [
    "Sensor_S1",
    "Sensor_S2",
    "Sensor_S3",
    "Sensor_S4"
]

# Check original missing values
print("Original missing values:")
print(cleaned_train[sensor_columns].isna().sum())

# Create missing-value indicators BEFORE filling anything
for col in sensor_columns:
    cleaned_train[col + "_missing"] = (
        cleaned_train[col].isna().astype(int)
    )

print("\nMissing indicators:")
print(
    cleaned_train[
        [col + "_missing" for col in sensor_columns]
    ].sum()
)

# ============================================================
# PREPROCESSING - STEP 1
# Reload the ORIGINAL raw training data
# ============================================================

train_raw = pd.read_excel(
    file_path,
    sheet_name="Training_Data"
)

print("Raw training data shape:", train_raw.shape)
print("\nMissing values in raw sensor data:")

print(
    train_raw[
        ["Sensor_S1", "Sensor_S2", "Sensor_S3", "Sensor_S4"]
    ].isna().sum()
)

# ============================================================
# PREPROCESSING - STEP 2
# Create preprocessing dataframe
# ============================================================

cleaned_train = train_raw.copy()

print("Rows:", len(cleaned_train))
print("Columns:", len(cleaned_train.columns))

# ============================================================
# PREPROCESSING - STEP 3
# Define columns
# ============================================================

feature_columns = [
    "Applied_Voltage_kV",
    "Load_Current_A",
    "Ambient_Temperature_C",
    "Test_Duration_min",
    "Sensor_S1",
    "Sensor_S2",
    "Sensor_S3",
    "Sensor_S4"
]

sensor_columns = [
    "Sensor_S1",
    "Sensor_S2",
    "Sensor_S3",
    "Sensor_S4"
]

id_column = "Test_ID"

regression_target = "Reference_Parameter"

classification_target = "Validity_Label"

print("Input features:")
print(feature_columns)

print("\nRegression target:", regression_target)
print("Classification target:", classification_target)
print("ID column:", id_column)

# ============================================================
# PREPROCESSING - STEP 4
# Create a SEPARATE copy for missing-value indicators
# ============================================================

indicator_train = train_raw.copy()

for col in sensor_columns:
    indicator_train[col + "_missing"] = (
        indicator_train[col].isna().astype(int)
    )

print("Missing-value indicators:")
print(
    indicator_train[
        [col + "_missing" for col in sensor_columns]
    ].sum()
)

# ============================================================
# PREPROCESSING - STEP 5
# Save dataset with missing-value indicators
# ============================================================

indicator_train.to_csv(
    "cleaned_training_with_missing_indicators.csv",
    index=False
)

print("File saved successfully.")
print("Shape:", indicator_train.shape)

# ============================================================
# PREPROCESSING - STEP 6
# Calculate median values for imputation
# ============================================================

medians = {}

for col in feature_columns:
    medians[col] = train_raw[col].median()

print("Median values:")

for col, value in medians.items():
    print(f"{col}: {value}")

## ============================================================
# PREPROCESSING - STEP 7
# Median imputation
# ============================================================

for col in feature_columns:
    cleaned_train[col] = cleaned_train[col].fillna(medians[col])

print("Missing values after imputation:")

print(
    cleaned_train[feature_columns].isna().sum()
)

# ============================================================
# PREPROCESSING - STEP 8
# Verify row count
# ============================================================

print("Original rows:", len(train_raw))
print("Cleaned rows:", len(cleaned_train))

assert len(train_raw) == len(cleaned_train)

print("\nSUCCESS: All 1000 rows have been retained.")

# ============================================================
# PREPROCESSING - STEP 9
# Verify ID and target columns
# ============================================================

assert cleaned_train["Test_ID"].equals(
    train_raw["Test_ID"]
)

assert cleaned_train["Reference_Parameter"].equals(
    train_raw["Reference_Parameter"]
)

assert cleaned_train["Validity_Label"].equals(
    train_raw["Validity_Label"]
)

print("Test_ID: unchanged")
print("Reference_Parameter: unchanged")
print("Validity_Label: unchanged")

# ============================================================
# PREPROCESSING - STEP 10
# Final verification
# ============================================================

print("Final shape:", cleaned_train.shape)

print("\nMissing values:")
print(cleaned_train.isna().sum())

print("\nFinal columns:")
print(cleaned_train.columns.tolist())

# ============================================================
# PREPROCESSING - STEP 11
# Save cleaned training dataset
# ============================================================

cleaned_train.to_csv(
    "cleaned_training_data.csv",
    index=False
)

print("SUCCESS!")
print("Saved: cleaned_training_data.csv")
print("Shape:", cleaned_train.shape)

# ============================================================
# FIX - Recreate BASIC cleaned dataset with 11 columns
# ============================================================

# Start from the original raw training data
basic_cleaned_train = train_raw.copy()

# Median imputation
for col in feature_columns:
    basic_cleaned_train[col] = basic_cleaned_train[col].fillna(
        train_raw[col].median()
    )

# Final check
print("Basic cleaned dataset shape:", basic_cleaned_train.shape)

print("\nColumns:")
print(basic_cleaned_train.columns.tolist())

print("\nMissing values:")
print(basic_cleaned_train.isna().sum())

basic_cleaned_train.to_csv(
    "cleaned_training_data.csv",
    index=False
)

print("SUCCESS!")
print("cleaned_training_data.csv saved.")
print("Shape:", basic_cleaned_train.shape)

# ============================================================
# Create indicator + imputed dataset
# ============================================================

indicator_train = train_raw.copy()

# Create indicators BEFORE imputation
for col in sensor_columns:
    indicator_train[col + "_missing"] = (
        indicator_train[col].isna().astype(int)
    )

# Median imputation
for col in feature_columns:
    indicator_train[col] = indicator_train[col].fillna(
        train_raw[col].median()
    )

print("Indicator + imputed dataset shape:", indicator_train.shape)

print("\nMissing values in input features:")
print(indicator_train[feature_columns].isna().sum())

print("\nMissing indicators:")
print(
    indicator_train[
        [col + "_missing" for col in sensor_columns]
    ].sum()
)

# ============================================================
# PREPROCESSING - STEP 12
# Create missing indicators + median imputation
# ============================================================

# Start from the ORIGINAL raw training data
indicator_train = train_raw.copy()

# ------------------------------------------------------------
# 1. Create missing-value indicators BEFORE imputation
# ------------------------------------------------------------

for col in sensor_columns:
    indicator_train[col + "_missing"] = (
        indicator_train[col].isna().astype(int)
    )

# ------------------------------------------------------------
# 2. Median imputation
# ------------------------------------------------------------

for col in feature_columns:
    indicator_train[col] = indicator_train[col].fillna(
        train_raw[col].median()
    )

# ------------------------------------------------------------
# 3. Verify
# ------------------------------------------------------------

print("Final shape:", indicator_train.shape)

print("\nMissing values in input features:")
print(
    indicator_train[feature_columns].isna().sum()
)

print("\nMissing-value indicators:")
print(
    indicator_train[
        [col + "_missing" for col in sensor_columns]
    ].sum()
)

# ============================================================
# PREPROCESSING - STEP 13
# Verify indicator dataset
# ============================================================

print("Shape:", indicator_train.shape)

print("\nColumns:")
print(indicator_train.columns.tolist())

# ============================================================
# PREPROCESSING - STEP 14
# Save indicator + imputed dataset
# ============================================================

indicator_train.to_csv(
    "cleaned_training_with_missing_indicators_imputed.csv",
    index=False
)

print("SUCCESS!")
print(
    "Saved: cleaned_training_with_missing_indicators_imputed.csv"
)
print("Shape:", indicator_train.shape)

# ============================================================
# PREPROCESSING - STEP 15
# Create preprocessing README
# ============================================================

readme_text = """
CPRI HACKATHON - DATA PREPROCESSING

RAW DATA
The original raw Excel file was not modified.

TRAINING DATA
1000 training records were retained.
No rows were removed.

INPUT FEATURES
1. Applied_Voltage_kV
2. Load_Current_A
3. Ambient_Temperature_C
4. Test_Duration_min
5. Sensor_S1
6. Sensor_S2
7. Sensor_S3
8. Sensor_S4

TARGET COLUMNS
Regression target:
Reference_Parameter

Classification target:
Validity_Label

IDENTIFIER
Test_ID

Test_ID is retained for identification and final output,
but should not be used as a model input feature.

MISSING VALUES
Missing values were present in Sensor_S1, Sensor_S2,
Sensor_S3 and Sensor_S4.

Missing numerical values were replaced using median
imputation.

Median values were calculated from the training data.

No rows were deleted because of missing values.

OUTLIERS
Unusual sensor values were not automatically removed.

SCALING
No feature scaling was performed during base preprocessing.

FEATURE ENGINEERING
No engineered features were added during preprocessing.
Feature engineering will be performed separately.

DATASET VERSIONS

1. cleaned_training_data.csv
   Basic cleaned dataset with 11 columns.

2. cleaned_training_with_missing_indicators_imputed.csv
   Cleaned dataset with 4 additional missing-value
   indicator columns.

MISSING-VALUE INDICATORS

Sensor_S1_missing = 1 if Sensor_S1 was originally missing,
otherwise 0.

Sensor_S2_missing = 1 if Sensor_S2 was originally missing,
otherwise 0.

Sensor_S3_missing = 1 if Sensor_S3 was originally missing,
otherwise 0.

Sensor_S4_missing = 1 if Sensor_S4 was originally missing,
otherwise 0.

The sensor values are median-imputed while the indicators
preserve information about whether the original value was
missing.

IMPORTANT
Test_ID should not be used as a model feature.
Reference_Parameter and Validity_Label are target columns.

The original raw Excel dataset remains unchanged.
"""

with open("preprocessing_README.txt", "w") as f:
    f.write(readme_text)

print("SUCCESS!")
print("Saved: preprocessing_README.txt")

from google.colab import files

files.download("cleaned_training_data.csv")

files.download(
    "cleaned_training_with_missing_indicators_imputed.csv"
)

files.download("preprocessing_README.txt")

